import type { Route } from "./+types/allPosts"; // <--- Auto-generated by v7

// 1. Get params in the LOADER (Best for Data/Supabase)
export async function loader({ params }: Route.LoaderArgs) {
  const page = params.pageNumber;
  return { page };
}

// 2. Get params in the COMPONENT (Best for UI)
export default function AllPosts({ loaderData, params }: Route.ComponentProps) {
  // Option A: From the loader (Pre-processed)
  const { page } = loaderData;

  // Option B: From the component props (Type-safe params!)
  const { pageNumber } = params;

  return (
    <div>
      <h1>All Posts: page: {pageNumber}</h1>
      <p>Data loaded for page: {page}</p>
    </div>
  );
}
